name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Test
    #   run: ./test.sh
    - name: Build
      run: ./run.sh psychedelic
