name: Unit Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies (Ubuntu)
      run: sudo apt-get install libopencv-dev valgrind
    - name: Test (Ubuntu)
      run: ./test.sh
  Mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Dependencies (Mac)
      run: ls -a ~; exit 1; brew install opencv llvm; alias clang
    - name: Test (Mac)
      run: ./test.sh
